from pydantic import BaseModel


class BookCreate(BaseModel):
    """
    schema used for creating or updating a book.

    fields
        title   the title of the book (required)
        author  the author of the book (required)
        year    publication year (optional)
    """

    title: str
    author: str
    year: int | None = None


class BookResponse(BaseModel):
    """
    schema returned when reading book data from the database.

    this schema includes the `id` field, which is automatically
    generated by the database.
    """

    id: int
    title: str
    author: str
    year: int | None = None

    class Config:
        """
        enables ORM mode so Pydantic can read SQLAlchemy model
        instances directly and convert them into this schema.
        """
        orm_mode = True
